#!/bin/bash -e

cat <<EOF
This is the s2i-ubuntu-graphviz-openjdk8 S2I image:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:

s2i build test/ s2i-ubuntu-graphviz-openjdk8 nginx-app

You can then run the resulting image via:
docker run -d -p 8080:8080 nginx-app
and see the test via http://localhost:8080
EOF
